name: kaski_nfc_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_riverpod: ^2.4.10
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  flutter_credit_card: ^4.1.0
  http: ^1.5.0
  device_info_plus: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kaski_logo.png"
  
flutter:

  uses-material-design: true

  assets:
    - assets/
